host: localhost
port: 9901
name: app
ssl: false
settings:
  enable_reuse_port: false
  task_enable_coroutine: true
  task_object: true
  task_worker_num: 8
  #    daemonize: true
  #    pid_file: ${app.runtime}/winter.pid
  #log_file: ${app.runtime}/logs/swoole_error.log
  log_level: 2 # 0 - 6
  log_rotation: '#{SWOOLE_LOG_ROTATION_HOURLY}'
  log_date_format: '%Y-%m-%d %H:%M:%S'
  open_tcp_keepalive: true
  tcp_keepidle: 4 # 4s没有数据传输就进行检测
  tcp_keepinterval: 1 # 1s探测一次
  tcp_keepcount: 5 # 探测的次数，超过5次后还没回包close此连接
  heartbeat_idle_time: 600 # 表示一个连接如果600秒内未向服务器发送任何数据，此连接将被强制关闭
  heartbeat_check_interval: 60 # 表示每60秒遍历一次
  enable_coroutine: true
  hook_flags: '#{SWOOLE_HOOK_ALL}'
  event_object: true